### ISSUE TITLE
Change the way filenames are accessed from SDLogger class

### ISSUE THREAD

**Issue by irowebbn** [krups/iss-software#11]
Since we have a pre-determined number of logfiles, just use a constant identifier to refer to each instead of using the function to get the identifier.

**Comment by ruffner** [comment]
Fixed. File IDs now #defined in config.h

**Comment by irowebbn** [comment]
Sounds good. Linking the commit here in case we need to reference later https://github.com/krups/iss-software/commit/24976840a6ee5b325d8b9afd1e13ff9b1c134eef
